### ISSUE TITLE
sin(5) numeric gives a value of $$ --0.756\,802\ldots $$

### ISSUE THREAD

**Issue by rs-mobitech** [cortex-js/compute-engine#100]
I am not sure if this is intended but the number here has two hyphens before it instead of the one that I would expect

<img width="773" alt="Screenshot 2023-08-25 at 16 01 48" src="https://github.com/cortex-js/compute-engine/assets/39233783/ce26bdea-1d5c-487d-9b17-af9d8be93cd5">

**Comment by arnog** [comment]
Fixed now.
