### ISSUE TITLE
Editable mathJSON once edited won't change again

### ISSUE THREAD

**Issue by rs-mobitech** [cortex-js/compute-engine#103]
Once a change has been made to the mathJSON field in the Cortex demo page, then the value of that field will no longer be updated, if the different example options are tapped on.  See below:

<img width="837" alt="Screenshot 2023-08-26 at 16 58 31" src="https://github.com/cortex-js/compute-engine/assets/39233783/6ffa2e24-e626-4420-a354-62d1146a34b3">

**Comment by arnog** [comment]
Fixed now.
