### ISSUE TITLE
Numeric evaluation of \sum_{i=0}^{25}\left(\frac{i}{10}\right) crashes 

### ISSUE THREAD

**Issue by rs-mobitech** [cortex-js/compute-engine#105]
I entered this expression:

<img width="399" alt="Screenshot 2023-08-31 at 15 24 19" src="https://github.com/cortex-js/compute-engine/assets/39233783/28cb6ea1-9968-4632-8b91-c9b657e3be3b">

and when trying to assign to the variable b

             parsedExpCanTrue = MathfieldElement.computeEngine.parse(mathLatex, {canonical:true});
             var b = parsedExpCanTrue.N();

it crashes with the following message

<img width="650" alt="Screenshot 2023-08-31 at 15 26 52" src="https://github.com/cortex-js/compute-engine/assets/39233783/11738b96-d0de-450c-b2f0-1de0d03eef31">

<img width="549" alt="Screenshot 2023-08-31 at 15 26 50" src="https://github.com/cortex-js/compute-engine/assets/39233783/a668921c-3d57-467f-a9a9-7ae3fe5ee9a0">

**Comment by arnog** [comment]
Works correctly now.
