### ISSUE TITLE
Numerical Evaluation external libraries

### ISSUE THREAD

**Issue by OleksiyPetroKovalenko** [cortex-js/compute-engine#110]
In the documentation, it's mentioned that:

- The 'bignum' mode utilizes the decimal.js library.
- The 'complex' mode is supported by the complex.js library.
- 
Could you please clarify if we need to incorporate these libraries ourselves? If not, how can we ensure that the most recent versions of these libraries are in use?

**Comment by arnog** [comment]
I doubt it, I'm using their latest versions.
