### ISSUE TITLE
Could you enhance your documentation by including more details about the LaTeX Dictionary?

### ISSUE THREAD

**Issue by OleksiyPetroKovalenko** [cortex-js/compute-engine#116]
**Is your feature request related to a problem? Please describe.**

I've noticed frequent mentions of this topic in your documentation. However, for those unfamiliar with the dictionary's layout and its nuances, the explanation falls short in its clarity, especially for newcomers.

Here is an example:

> Remove the `PlusMinus` entry from the default dictionary...

This is a short comment that appears in the example code.  Maybe the Latex dictionary is described in detail somewhere, but not knowing where more information is available, then the comment is not sufficient for someone learning.  Does this effect, what we enter in MathLive, or if not then what does it effect and how could we test out that it works.  All is unfortunately unclear to me. 

**Describe the solution you'd like**

Could you explain the utilization and application of the Latex dictionary? I'd appreciate a comprehensive guide detailing its contents, various representations of entries, and the underlying rationale.

**Describe alternatives you've considered**

Despite investing significant time trying to grasp this, it remains elusive.

**Additional context**

A straightforward and easily digestible explanation would be advantageous to all. While the current documentation is commendable, its complexity leans more towards those already well-versed in the subject, rather than catering to novices.

**Comment by arnog** [comment]
The documentation has been updated: https://cortexjs.io/compute-engine/guides/latex-syntax/#customizing-the-latex-dictionary
