### ISSUE TITLE
The requested module '@cortex-js/compute-engine/dist/compute-engine.min.esm.js' is a CommonJS module, which may not support all module.exports as named exports.

### ISSUE THREAD

**Issue by Seancheey** [cortex-js/compute-engine#121]
I'm using sveltekit + vite, and when I run `npm  run build`, the following error came up. Here is an error I found:

```
import { ComputeEngine } from "@cortex-js/compute-engine/dist/compute-engine.min.esm.js";
         ^^^^^^^^^^^^^
SyntaxError: Named export 'ComputeEngine' not found. The requested module '@cortex-js/compute-engine/dist/compute-engine.min.esm.js' is a CommonJS module, which may not support all module.exports as named exports.
```

Also `npm run test:unit` raises error:  (it uses `vitest` in the backend)
<img width="1317" alt="Screen Shot 2023-10-08 at 5 07 37 PM" src="https://github.com/cortex-js/compute-engine/assets/8847505/88527482-afeb-4f29-82ca-ffe1bc443429">

**Comment by volesen** [comment]
@Seancheey, which version of `vite` are you using?
