### ISSUE TITLE
Only a nonstandard negation operator parses

### ISSUE THREAD

**Issue by nathancarter** [cortex-js/compute-engine#134]
## Description

The MathLive editor supports multiple ways to express the same logical negation symbol, but only one of them actually parses, and it is not one I had ever heard of.

### Steps to Reproduce

After loading MathLive, I try these at the console.

```js
// Other logical operators work as expected:
MathfieldElement.computeEngine.parse( 'A \\wedge B' ).json
// ==> ['And','A','B']
//     Great!  Works as expected!
MathfieldElement.computeEngine.parse( 'A \\vee B' ).json
// ==> ['Or','A','B']
//     Great!  Works as expected!
MathfieldElement.computeEngine.parse( 'A \\implies B' ).json
// ==> ['Implies','A','B']
//     Not standard LaTeX, but I'm not arguing.  That's fine.

// Now, the problem I'm reporting:
MathfieldElement.computeEngine.parse( '\\neg A' ).json
// ==> ['Error',['ErrorCode','\'unexpected-command\'','\'\\neg\''],['LatexString','\'\\neg\'']]
//     That means the most common negation symbol AFAIK isn't respected.
MathfieldElement.computeEngine.parse( '\\not A' ).json
// ==> ['Error',['ErrorCode','\'unexpected-command\'','\'\\not\''],['LatexString','\'\\not\'']]
//     This was just a guess because we had "implies" spelled out, so I was experimenting...
MathfieldElement.computeEngine.parse( '\\lnot A' ).json
// ==> ['Not','A']
//     Works but it's an unusual operator name.
//     The only way I discovered this symbol was by using the keyboard in the MathLive widget,
//     then inspecting under the hood what it was it had created.
```

### Actual Behavior

The system accepts only `\lnot` as a parse-able negation operator.

### Expected Behavior

I expected the (standard?) `\neg` operator to be parse-able.

### Environment

**MathLive version**  Latest from CDN on Dec 7, 2023, which is CortexJS Compute Engine 0.22.0.

**Operating System** macOS 12.4

**Browser** Brave

**Comment by arnog** [comment]
Both `\neg` and `\lnot` are used. See https://www.bu.edu/math/files/2013/08/LongTeX1.pdf, https://tex.stackexchange.com/questions/430677/what-is-the-difference-between-lnot-and-neg or https://www.cis.upenn.edu/~cis1600/current/files/resources/useful_latex_commands.pdf.

I'm not sure if one is more popular than the the other, but if you have any reference on that I'd be interested...

**Comment by nathancarter** [comment]
Okay, good point, I should be more specific, sorry.  As your second reference points out, there isn't a visual or semantic difference between `\neg` and `\lnot`.  Furthermore, you can enter both of them in MathLive.  That's why I was surprised to find out that one of them parses into logical negation while the other one generates a parsing error.  That's unexpected.  I would think that if the appearance and accepted meaning of both is identical, then the behavior of both of them in the parser should also be identical.
