### ISSUE TITLE
Incorrect answer for isEqual when decimals are attached to variables

### ISSUE THREAD

**Issue by johnsmithecon** [cortex-js/compute-engine#135]
Incorrect answer for isEqual when decimals are attached to variables.

### Steps to Reproduce

let expr1 = engine.parse("2(13.1x+1)");
let expr2 = engine.parse("26.2x+2");
console.log("expr1 is equal to expr2: ", expr1.isEqual(expr2));

### Actual Behavior

The result is "expr1 is equal to expr2: false"

### Expected Behavior

"expr1 is equal to expr2: true"

**Comment by arnog** [comment]
Works now.
