### ISSUE TITLE
Matching documentation issue

### ISSUE THREAD

**Issue by stefnotch** [cortex-js/compute-engine#14]
The match function is defined as follows

https://github.com/cortex-js/compute-engine/blob/fd21f07a12af2dc0bb792b8633dc167737d35edf/src/compute-engine/patterns.ts#L194-L197

However, this appears to contradict [the documentation](https://cortexjs.io/compute-engine/guides/patterns-and-rules/), which has examples like
```ts
console.log(match(['Add', '1', 'x'], ['Add', '_a', '_a']));
```

**Comment by arnog** [comment]
The documentation is correct. The labels of the `match()` function are wrong.

**Comment by arnog** [comment]
Fixed now.
