### ISSUE TITLE
[FEATURE] Evaluate the result of an expression in specific units

### ISSUE THREAD

**Issue by rwmorton** [cortex-js/compute-engine#140]
**Is your feature request related to a problem? Please describe.**
It would be nice to do the computation in specific units (ie. radians or degrees).

**Describe the solution you'd like**
To be able to tell the compute engine what units you would like to use for trig functions (for example).

**Comment by arnog** [comment]
I think this is a duplicate of #82.

**Comment by arnog** [comment]
Not response in several weeks. Closing.
