### ISSUE TITLE
Compute engine can't parse the latex "\log_{frac{122}{2}} (b^{2c})"

### ISSUE THREAD

**Issue by renanlr** [cortex-js/compute-engine#142]
## Description

Compute engine can't parse the latex `\log_{\frac{122}{2}} (b^{2c})`

### Steps to Reproduce

1. Run the following code:

```diff
- const expr = ce.parse(String.raw`\log_{frac{122}{2}}(b^{2c})`);
+ const expr = ce.parse(String.raw`\log_{\frac{122}{2}}(b^{2c})`);
console.log("Errors:", expr.errors);
```

### Actual Behavior
```diff
- Errors: [Error("invalid-identifier", "frac\{122\}\{2\}")]
+ Errors: [Error("invalid-identifier", "\frac\{122\}\{2\}")]
```

### Expected Behavior

The latex should be parsed correctly
```
Errors: []
```

### Environment

**MathLive version** 0.23.1

**Operating System** macOS 13.4.1

**Browser** 
It's failing the same way in Safari, Chrome and Firefox

**Comment by renanlr** [comment]
Sorry, my mistake,
But even when I add the "\" the problem persists.

**Comment by arnog** [comment]
The `Log` function expects either a number or an identifier in the subscript. Did you actually intend to have an expression there?
