### ISSUE TITLE
[FEATURE] Include support for phi

### ISSUE THREAD

**Issue by rwmorton** [cortex-js/compute-engine#148]
**Is your feature request related to a problem? Please describe.**
It would be nice to include the phi symbol. What I do currently is I parse the latex and replace any occurence of \phi with the value of phi itself as a latex fraction.

eg. `useLatex = useLatex.replaceAll(/\\phi/g, '\\frac{1 + \\sqrt{5}}{2}')`

**Describe the solution you'd like**
It would be nice for compute-engine to support phi natively.

**Describe alternatives you've considered**
Pre-processing of the latex before giving it to compute-engine.

**Comment by arnog** [comment]
The LaTeX command `\varphi` already maps to `GoldenRatio`.

If you want the `\phi` command to also map to `GoldenRatio`, use:

```ts
ce.latexDictionary = [
  ...ce.latexDictionary,
  {
    latexTrigger: "\\phi",
    parse: "GoldenRatio",
  }
];
```

**Comment by rwmorton** [comment]
Ah great thank you so much!
