### ISSUE TITLE
Arbitrary unicode characters

### ISSUE THREAD

**Issue by stefnotch** [cortex-js/compute-engine#16]
I'd love it if the compute-engine could handle arbitrary Unicode characters and parse them as variable names.
A silly example would be
`\begin{equation*} 🍕+3 \end{equation*}`

A more reasonable example would be variable names in a different language, I suppose.

**Comment by arnog** [comment]
The Compute Engine now parses emoji as well as non-Latin characters correctly. Due to the complexities of Unicode, it's not "arbitrary" characters, but a very extended set. See https://cortexjs.io/math-json/#identifiers
