### ISSUE TITLE
Simplify expression with --

### ISSUE THREAD

**Issue by remiangot** [cortex-js/compute-engine#173]
## Description

Simplification with -- or ++ doesn't work

### Steps to Reproduce

const expr1 = engine.parse('3--5')
expr1.simplify()
console.log(expr1.latex)

const expr2 = engine.parse('3++5')
expr2.simplify()
console.log(expr2.latex)

### Actual Behavior

3--\times5
3++\times5

### Expected Behavior

3+5
3+5

**Comment by arnog** [comment]
It works now.
