### ISSUE TITLE
Grouping and parenthesis

### ISSUE THREAD

**Issue by leerobert** [cortex-js/compute-engine#2]
Currently having issues trying to serialize parenthesis grouped expressions. It looks like we might neeed a way to clean mathlive latex into math json expected strings. (Converting `\\mleft(` into `(`, etc...)

```json
"x\\mleft(x-4\\mright)"
```

Is serialized to

```js
[ "Subtract", [ "Multiply", "x", "\\mleft", [ "Parentheses" ], "x" ], [ "Multiply", { "num": "4" }, "\\mright" ] ]
```

**Comment by stefnotch** [comment]
Seems to work now. https://cortexjs.io/compute-engine/demo/
