### ISSUE TITLE
1/ln(0) evaluates numerically to 1

### ISSUE THREAD

**Issue by mdavis7168** [cortex-js/compute-engine#205]
## Description

As the title says

### Steps to Reproduce

This is reproducible on the [MathLive demo site](https://cortexjs.io/mathlive/demo/):
![Screenshot from 2024-10-15 22-00-02](https://github.com/user-attachments/assets/667904e5-c647-4f4f-8286-bd6e0e068310)

### Actual Result

1/ln(0) evaluates numerically to 1

### Expected Result

1/ln(0) should be undefined because ln(0) is undefined.

### Environment

MathLive version 0.101.1.
ComputeEngine version: 0.26.2

**Comment by arnog** [comment]
`1/ln(0)` now returns `0`, consistent with Mathematica (`ln(0)` is -∞, also consistent with Mathematica).
