### ISSUE TITLE
`\complement` doesn't parse correctly

### ISSUE THREAD

**Issue by bengolds** [cortex-js/compute-engine#21]
The parser doesn't seem to handle Set complement correctly:

![CleanShot 2021-10-18 at 16 44 49](https://user-images.githubusercontent.com/446007/137821150-49b30a15-6a5b-411a-a851-2ce5bcfa3818.png)

This appears to be `A^\complement`, which the latex parser interprets as:
```[ 'Power', 'A', '\complement']```

The other approach we considered was simply `A\complement` -- but the parser interprets that as:
```['Complement', 'A', 'Missing']```

**Comment by arnog** [comment]
The parser now handles `\complement` as an exponent.
