### ISSUE TITLE
Custom function parsing fails

### ISSUE THREAD

**Issue by debjitbis08** [cortex-js/compute-engine#222]
## Description

When declaring custom function, the parsing fails with error `TypeError: i is undefined`

### Steps to Reproduce

I tried the example provided in the [docs](https://cortexjs.io/compute-engine/guides/augmenting/#defining-a-function),

https://jsfiddle.net/debjitbis08/gabzLpqo/4/

```javascript
import { ComputeEngine } from 'https://unpkg.com/@cortex-js/compute-engine?module';

const ce = new ComputeEngine();

console.log('Declaring double...');
ce.declare("double", {
  signature: {
    domain: "Functions",
    evaluate: (ce, args) => ce.number(args[0].value * 2),
  },
});
console.log(ce.parse("2 * 3").json);
const expr = ce.parse("\\operatorname{double}(3)");
console.log(expr.json);
```

### Actual Result

This the output in the console.

```
"Declaring double..."
["Multiply", 2, 3]
"TypeError: i is undefined"
```

### Expected Result

Expected to see `["double", 3]`

### Environment

Tested that it works as expected in `0.25.1`

**Comment by arnog** [comment]
The documentation is out of date. The correct syntax is:

```
ce.declare('double', {
  signature: 'number -> number',
  evaluate: ([x], { engine: ce }) => ce.number(x.re * 2),
});
```

**Comment by debjitbis08** [comment]
> The documentation is out of date. The correct syntax is:
> 
> ```
> ce.declare('double', {
>   signature: 'number -> number',
>   evaluate: ([x], { engine: ce }) => ce.number(x.re * 2),
> });
> ```

Thank you. This works.
