### ISSUE TITLE
Improper N evaluation for certain fractions

### ISSUE THREAD

**Issue by paulgrudnitski** [cortex-js/compute-engine#24]
N(3 + 1/4)   -->  3.75
N('3+\frac{1}{4}') --> 3.75

![image](https://user-images.githubusercontent.com/898605/144452621-7ce48315-0ec0-4d61-b8c4-d0f0df70e597.png)

**Comment by strickinato** [comment]
This appears to be fixed in `0.4.3`

![image](https://user-images.githubusercontent.com/7566896/160016281-5cdafe15-c3d2-456b-a7d2-f01558b66988.png)

```
> p.parse("3+1/4").N().json
3.25
```
