### ISSUE TITLE
² key should apply power of two instead of acting as a character

### ISSUE THREAD

**Issue by DegrangeM** [cortex-js/compute-engine#35]
The ² key is on AZERTY keyboard (top left).
Pressing it should apply a power of two (with the cursor not in the power).

**Comment by arnog** [comment]
Could you include a picture of which key you're talking about?

**Comment by DegrangeM** [comment]
![image](https://user-images.githubusercontent.com/53106394/159138478-e3912dd5-a2fa-492f-931a-086678d2d49b.png)

**Comment by DegrangeM** [comment]
event.key : ²
event.which : 222
event.code : Backquote

**Comment by arnog** [comment]
OK, thanks. It's not a super common key, but this layout apparently exists on some Windows and Linux PCs.

**Comment by arnog** [comment]
OK, I've checked in a fix, but I unfortunately have no way of testing it... 
8a48bc4d49657e54caf3b6b0a0355da530a8ad16

**Comment by DegrangeM** [comment]
This works, thanks !
