### ISSUE TITLE
`0.5.0` doesn't include LatexSyntax

### ISSUE THREAD

**Issue by bengolds** [cortex-js/compute-engine#42]
I've installed the latest version of `compute-engine` (0.5.0) and am trying to call `LatexSyntax.getDictionary`; however, it seems that the exported `dist/compute-engine.min.js` doesn't actually include `LatexSyntax`'s code. The types seem to indicate that a line like this should work:

```
import { ComputeEngine, LatexSyntax } from '@cortex-js/compute-engine';
```

However, this fails when running in the browser. You can also reproduce this by running

```
$ node
> const ce = require('./dist/compute-engine.min.js')
undefined
> ce
{ ComputeEngine: [class (anonymous)], version: '0.5.0' }
>
```

Is there another way to import `LatexSyntax`, now that it was dropped from `math-json.min.js`?

**Comment by arnog** [comment]
Ah, yes...
`LatexSyntax` is not visible because there's no point (I think) in creating a `LatexSyntax` instance without a `ComputeEngine` (the two used to be more separated, but correct parsing actually requires access to a `ComputeEngine` instance).

I did forget about the static `LatexSyntax.getDictionary()`, though... One option would be to re-export it via ComputeEngine, something like `ComputeEngine.getLatexDictionary()`. Would that work for you?

**Comment by bengolds** [comment]
That would work great! That's the only use we have for `LatexSyntax`.

**Comment by bengolds** [comment]
If you get a chance, can you cut a new release with this feature?

**Comment by arnog** [comment]
mathlive `0.71.0` should have the new static method.

**Comment by bengolds** [comment]
I don't see anything related to `getDictionary` or `getLatexDictionary` in [the release notes or diff for 0.71.0](https://github.com/arnog/mathlive/compare/v0.70.0...v0.71.0) -- is this the same as `mf.getOptions('macros')`?

**Comment by arnog** [comment]
Oh... sorry, I got confused. It's the Compute Engine that thas the `getLatexDictionary()` static method, but the version of the Compute Engine that has this is not yet integrated into MathLive.

**Comment by bengolds** [comment]
Yeah, and it doesn't look like there's a new release of Compute Engine with that static method. We actually import Compute Engine directly as well, so if you have a chance to cut a new version with the static method we'll be good to go.

**Comment by MatousAc** [comment]
As far as I can tell, this still isn't working, right? I'm trying `getLatexDictionary()` in [this Codepen](https://codepen.io/MatousAc/pen/ZEMWLbJ),  but it isn't defined. Maybe I'm doing it wrong? I just want the proper way of viewing the engine's Latex dictionary.
I'm trying:
~~~
import { ComputeEngine } from 'https://unpkg.com/@cortex-js/compute-engine?module';

let engine = new ComputeEngine();
console.log(engine.parse("2 + 3").json)  // ["Add",2,3]
console.log(engine.getLatexDictionary()) // not a f(x)
~~~
I can get the engine to parse things, but I can't get `getLatexDictionary()` to work.
Thanks.

**Comment by MatousAc** [comment]
Sorry to clutter the comment section.
I think the issue may be that I'm calling the function on an instance of a compute engine rather than using `ComputeEngine.getLatexDictionary()`. If that's the case, I'll open an issue for a follow-up question at some point.

**Comment by arnog** [comment]
@MatousAc yes, `getLatexDictionary()` is a static method, so you invoke it by using `ComputeEngine.getLatexDictionary()`.

**Comment by MatousAc** [comment]
Alright. Makes sense. I am used to this structure in other languages like Java or C++, but I haven't quite explored JS thoroughly enough to take all of this into account properly yet. Thanks.

Before I open a suggested feature issue, am I correct in assuming that [this documentation](https://cortexjs.io/compute-engine/guides/latex-syntax/#customizing-the-latex-dictionary) shows the only method for extending the latex dictionary? That is, you must create a new instance of ComputeEngine each time you want to extend the latex dictionary?

**Comment by arnog** [comment]
That's correct.
