### ISSUE TITLE
Error after simplify

### ISSUE THREAD

**Issue by smaxx73** [cortex-js/compute-engine#45]
Hi, here is my code : 
```
const engine = new ComputeEngine()
expression = '2+\\frac{2+x}{2}'
expression2 = engine.parse(expression).simplify().latex
```

After printing expression = expression2 the result is : 
![image](https://user-images.githubusercontent.com/17359037/172799752-1ca08181-6619-4684-ae7e-7794120fa93d.png)

**Comment by arnog** [comment]
The result is now `3+\frac{x}{2}`
