### ISSUE TITLE
"Integrate" doesn't work

### ISSUE THREAD

**Issue by smaxx73** [cortex-js/compute-engine#46]
This code : 
```
const expr = ce.parse('x^2').json
ce.box(['Integrate', expr, ['Element', 'x', ['Interval', 0, 1]]]).latex
console.log(calculintegrale)
```
returns
`\mathrm{Integrate}(x^{2}, x\in ) `

**Comment by rs-mobitech** [comment]
+1 - Also hoping this feature could be added.  

I would love to be able to work on this myself, but it's way beyond my skill level .

**Comment by arnog** [comment]
```js
const expr = ce.parse('x^2').json;
const calculintegrale = ce.box([
    'Integrate',
    expr,
    ['Tuple', 'x', 0, 1],
  ]).latex;
console.log(calculintegrale);
// -> \int^{1}_{0}\!x^2\,\mathrm{d}x
```

Works now. Note that the second argument of `"Integrate"` is a `Tuple` of the index variable, the lower bound and the upper bound.
