### ISSUE TITLE
Can not parse "\sum"

### ISSUE THREAD

**Issue by ozkanbatuhan** [cortex-js/compute-engine#54]
I'm trying to parse a summation equation such as 

![Screenshot 2022-09-22 125520](https://user-images.githubusercontent.com/58174016/191718227-0e7983ef-920d-4c69-9c85-b5f60b058262.png)

and get an error as below;

![Screenshot 2022-09-22 130549](https://user-images.githubusercontent.com/58174016/191719461-ee58c293-c2f5-4e0e-b05e-5b8cf281e8b5.png)

Most of the summation cases got similar errors. It recognizes exponentiation instead of summation.

Thanks!

**Comment by arnog** [comment]
The parsing of `\sum` (and `\prod`) has been fixed.
