### ISSUE TITLE
Substituting a variable with 0 evaluates the equation without the 0 substitution

### ISSUE THREAD

**Issue by mightykillrr** [cortex-js/compute-engine#57]
>`@cortex-js/compute-engine`: `v0.8.0` from npm
>`vue`: `v3.2.40`
>Minimal Stackblitz demo: https://stackblitz.com/edit/vue-xsgxaq?file=src/App.vue

### What's happening
Substituting any variable with 0 returns an evaluated equation with the variable substituted with 0 untouched.

### What should happen
The variable should be treated as 0 and the equation should evaluate as normal

### Steps to Reproduce
1. Create a new ComputeEngine
2. Parse a latex equation with the created CE. (take `a+b+c` as example)
3. Substitute the variables with any values but **make sure one of them is 0**
4. Evaluate and check the output

### Quick Demonstration
**Equation**: `abc`
**Variables**: `a = 5, b = 0, c = 10`
**Expected Output**: `0` (since 5x0x5)
**Actual Output**: `50b`

**Comment by arnog** [comment]
Fixed now.
