### ISSUE TITLE
Examples from docs for replace do not work as described. 

### ISSUE THREAD

**Issue by shidel-dev** [cortex-js/compute-engine#63]
When executing the examples from [here](https://cortexjs.io/compute-engine/guides/patterns-and-rules/#applying-rewrite-rules) I aways observe the replace function returning null, and do not get the described behavior. Maybe the api has changed?

**Comment by arnog** [comment]
Yes, there was a typo in the example *and* the API has changed:

```ts
const squareRule = ce.rules([
  [
    ['Multiply', '_x', '_x'],
    ['Square', '_x'],
  ],
]);

ce.box(['Multiply', 4, 4]).replace(squareRule);
// ➔ ['Square', 4]


ce
  .box(['Multiply', 4, 4])
  .replace(
    ce.rules([
      [
        ['Multiply', '_x', '_x'],
        ['Square', '_x'],
      ],
    ])
  );
// ➔ 17
```
