### ISSUE TITLE
use degree in trigonometric functions

### ISSUE THREAD

**Issue by BlueCat0** [cortex-js/compute-engine#64]
move from https://github.com/arnog/mathlive/issues/1721

expect use degree with trigonometric functions
![2022-11-15_10-47-35](https://user-images.githubusercontent.com/16792362/201814294-dd1d541e-12c5-4a37-bbf5-0539ebbda98a.png)

is there anyway to support it?

![2022-11-15_10-44-12](https://user-images.githubusercontent.com/16792362/201813858-ae8c4198-8b22-4940-a2c9-3a0833394325.png)

**Comment by arnog** [comment]
Support for the `["Degrees"]` expression has been added.  It is available in LaTeX via `\deg`, `\degree` and `^\circ`.
