### ISSUE TITLE
Symbols with Subscript

### ISSUE THREAD

**Issue by fabiastisch** [cortex-js/compute-engine#66]
Hello 😃,
is it possible to use symbols with multiple subscripts to one Symbol or Variable, so that would work?:

```js
expr = expr.subs({"n": 4});     // working
expr = expr.subs({"f_1": 5});   // working
expr = expr.subs({"f_a": 5});   // working
expr = expr.subs({"f_ab": 5});  // not working
expr = expr.subs({"f_abc": 5}); // not working
expr = expr.subs({"f_{abc}": 5}); // not working (latex version)
expr = expr.subs({"f_a12": 5}); // not working
```

**Comment by arnog** [comment]
I'm not sure what you mean by "working" and "not working". When filing an issue, it is recommended to include the code you ran, the result you obtained and the result you expected.

I tried:

```ts
console.log(ce.box("f_abc").subs({f_abc: 5}).numericValue);
```
and I got `5` as expected.

Are you trying instead to **parse** some LaTeX with some subscripts and not getting what you expect? 

For the subscript to be interpreted as part of the symbol it must either be a number or a text command, i.e. `f_1` or `f_{\text{abc}}`. 

If you're expecting `f_{abc}` to be interpreted as the symbol `f_abc`, could you give me some examples (from real life) of symbols that would have this format?

**Comment by arnog** [comment]
No update in a long time. Closing.
