### ISSUE TITLE
Parsing fails when an exponent is bracketed

### ISSUE THREAD

**Issue by JackWH** [cortex-js/compute-engine#67]
The engine fails to evaluate simple expressions like `2^(3/2)`.

This issue (or a similar one) appears to be present in MathLive as well, which only sets the opening bracket in superscript.

It looks like the parser is misreading the delimiter somehow:

```json
[
  "Sequence",
  ["Error", "'missing'", ["Latex", "'^'"]],
  [
    "Error",
    ["ErrorCode", "'expected-close-delimiter'", ")"],
    ["Latex", "'('"]
  ]
]
```

This is using the latest releases of both MathLive and Cortex. Let me know if there's any more info I can help with, thanks! 🙏

**Comment by arnog** [comment]
I don't know how you got that result. It's working fine for me.

Did you try to do `ce.parse("2^(3/2)")`? The argument to the `parse()` function is a LaTeX string, so using the valid LaTeX syntax this should be: `ce.parse("2^{\\frac{3}{2}}")`.

I'm not sure what the issue in MathLive you're referring to is either. Could you describe what you did and what you see?

**Comment by JackWH** [comment]
@arnog Thanks, appreciate the clarification — I think I misunderstood two unrelated issues...

I'm normally passing LaTeX to the engine but this caught me off guard as it was such a simple expression, so I assumed it would be valid. When I saw the Cortex error I also tried pasting `2^(3/2)` directly into MathLive — but the vertical placement of the superscript was rendered incorrectly.

After noticing a [changelog entry](https://github.com/arnog/mathlive/blob/master/CHANGELOG.md#unreleased) about the bug, I put two and two together... Having forgotten it was never even LaTeX in the first place 😅
