### ISSUE TITLE
parsing \leq to mathJson gives Equal not LessEqual

### ISSUE THREAD

**Issue by sunki-hong** [cortex-js/compute-engine#69]
While 4 <= k are parsed as  ["LessEqual", 4, "k"] 4 \leq k gives ["Equal", 4, "k"] which seems awkward

Image 1 - Typing 4 \leq k 
<img width="800" alt="image" src="https://user-images.githubusercontent.com/27687176/208111335-d8c795e5-2766-4259-bed7-652689830b4a.png">

Image 2 - Typing 4 <= k 
<img width="547" alt="image" src="https://user-images.githubusercontent.com/27687176/208111543-29f9f15f-226a-467b-a419-461900c481fb.png">

ps Thanks for the amazing library
I'm really loving it 👍

**Comment by solve-selander** [comment]
Having the same issue with an implementation im working on, would love a fix for it :) Also a big fan of the library and editor!

**Comment by solve-selander** [comment]
hey @sunki-hong , have you found any work around for this one, or are you just not using \leq for now? :)
