### ISSUE TITLE
missing latex logic dictionary definitions

### ISSUE THREAD

**Issue by SamuelScheit** [cortex-js/compute-engine#70]
If I try to parse the latex string `x \lor x`
The compute engine fails to parse the string with the following error:
```js
["Sequence","x",["Error",["ErrorCode","'unexpected-command'","'\\lor'"],["Latex","'\\lor'"]],"x"]
```

It seems like the [`DEFINITIONS_LOGIC` dictionary](https://github.com/cortex-js/compute-engine/blob/main/src/compute-engine/latex-syntax/dictionary/definitions-logic.ts) is missing logic operators like (OR, NOT, AND, IMPLIES, EQUIVALENT).

**Comment by arnog** [comment]
This has now been fixed.
