### ISSUE TITLE
Relation to the Mathematica

### ISSUE THREAD

**Issue by JerryI** [cortex-js/compute-engine#80]
Was it inspired by Mathematica's ;)
```mathematica
ExportString[x^2, "ExpressionJSON"]
```

PS: Great project and a really powerful math editor

**Comment by arnog** [comment]
It actually wasn't! I only discovered ExpressionJSON a long time after I had been developing MathJSON. It's fascinating to see how similar they are, though. Convergent evolution, I suppose.
