### ISSUE TITLE
Order of operations is incorrect with summation  \sum

### ISSUE THREAD

**Issue by sdlauer** [cortex-js/compute-engine#81]
![image](https://github.com/cortex-js/compute-engine/assets/8899741/bb5c4f65-017b-4f9c-bcbd-88b30e3f5a5c)
This image was generated from input here:  https://cortexjs.io/compute-engine/demo/
with:  $$ 7\times\left(\sum_{i=1}^{25}\frac{i-1}{10}\right)+1 $$ and  $$ 7\times\sum_{i=1}^{25}\frac{i-1}{10}+1 $$ 

Both of the sums in the image should evaluate to 211.  Implied parentheses for summation are ignored.
NOTE working instance of implied parentheses:  $$ \cos3+1 $$ evaluates same as $$ 1 + \cos(3) $$

**Comment by arnog** [comment]
Fixed in `@cortex-js/compute-engine@0.12.3`
