### ISSUE TITLE
Evaluate trig functions with angles in degrees

### ISSUE THREAD

**Issue by markhats** [cortex-js/compute-engine#82]
Hello

Is it possible to force angles to be treated as degrees when evaluating trig functions?

For example, at the moment:
```
const testExp = ce.parse('\\sin 90');
testExp.N().valueOf();
```
evaluates as `0.8939966636005579`.

However, I would like to set a 'degrees' mode where the answer would be `1`.

Thanks.

**Comment by arnog** [comment]
You can specify the angle in degrees, i.e. `ce.parse("\\sin 90\\degree").N().valueOf()` returns 1. But there's no way to change the expected argument of the trig functions.

**Comment by markhats** [comment]
Thanks for the info @arnog . I was really looking for a way to treat angles as degrees in all (potentially deeply nested) trig functions. Maybe some sort of global setting I guess. I suppose I could try some sort of auto-insertion of `\\degree` before parsing but this seems a bit of a non-optimal thing to do.

**Comment by rs-mobitech** [comment]
+1

**Comment by arnog** [comment]
The `ce.angularUnit` property can be used to specify how unitless angle values should be interpreted:
- `"rad"`: radians, 2π radians is a full circle
- `"deg"`: degrees, 360 degrees is a full circle
- `"grad"`: gradians, 400 gradians is a full circle
- `"turn"`: turns, 1 turn is a full circle

The default is `"rad"`.

**Comment by rwmorton** [comment]
Thank you @arnog for the speedy response. A quick test looks like it doesn't work as expected? Am I doing something wrong here?

![image](https://github.com/cortex-js/compute-engine/assets/95928533/8b55c28e-88c3-4c76-ab6e-7078e376d61b)

**Comment by rwmorton** [comment]
Thank you @arnog will keep testing and hopefully find out what's going on with my setup. In the meantime possibly also another bug, `\arccos(0.5)6` doesn't evaluate properly. It should be 3. That's why I had the inverse trig functions in extra parentheses.

![image](https://github.com/cortex-js/compute-engine/assets/95928533/f8b5fab1-f8f1-4958-a238-3e78822f0bbc)

**Comment by rwmorton** [comment]
Thank you @arnog will keep testing and hopefully find out what's going on with my setup. In the meantime possibly also another bug, \arccos(cos(0.5))6 doesn't evaluate properly. It should be 3. That's why I had the inverse trig functions in extra parentheses.

![image](https://github.com/cortex-js/compute-engine/assets/95928533/d3a99fdd-002a-4dec-8e91-a2e1c8b634ce)

**Comment by arnog** [comment]
The arccos function is spelled "arccos".

![Uploading Screenshot 2024-03-04 at 20.40.07.png…]()

**Comment by rwmorton** [comment]
Thank you

**Comment by rwmorton** [comment]
Thank you

**Comment by rwmorton** [comment]
> It's very hard to debug from a screenshot, but it works fine for me (I've simplified the LaTeX: you don't need all those extra braces).
> 
> ![Screenshot 2024-03-04 at 19 40 14](https://private-user-images.githubusercontent.com/760798/309974772-9b40dbff-d84a-45b3-8151-8d8523ddf77b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MTQ1NjUsIm5iZiI6MTcwOTYxNDI2NSwicGF0aCI6Ii83NjA3OTgvMzA5OTc0NzcyLTliNDBkYmZmLWQ4NGEtNDViMy04MTUxLThkODUyM2RkZjc3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwNDUxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wM2I5M2EwNWU0YTNmZTUwMTQxNzIzZDBjZDA3MjY1YWI5ZjE3ZDVhODM4NzFiZjQ2M2Q1NjMxNTdjYTVmZThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c-riOuPhLBDN3c6dBtg9hSxIvBnLmBIGu3QL3oTnk24)

`import { ComputeEngine } from '@cortex-js/compute-engine'

const ce = new ComputeEngine()

ce.angularUnit = 'deg'
const latex = '\\arccos(\\cos(45))'
const expr = ce.parse(latex)
const x = expr.N().value

console.log('ce.angularUnit =', ce.angularUnit)
console.log('expr.latex =', expr.latex)
console.log('expr =', JSON.stringify(expr.json))
console.log(`expr.N().value = ${x}`)
`

Am I doing something wrong here? I'm on version `"@cortex-js/compute-engine": "^0.24.1"`

**Comment by arnog** [comment]
Thank you for sharing your code. It looks correct. However, those changes are in the main branch but have not been published to npm yet. You can look at the CHANGELOG file for more info.

**Comment by rwmorton** [comment]
Ah that makes sense, thank you!

**Comment by arnog** [comment]
I've added support for constructible values when the unit is not radians.
Note that tan(90) is ComplexInfinity (or undefined when converting to a JS value).

**Comment by rwmorton** [comment]
Thank you very much @arnog working now!
