### ISSUE TITLE
isEqual,  ce.box(['Equal', lhs, rhs]).evaluate()

### ISSUE THREAD

**Issue by dallin-mclaughlin** [cortex-js/compute-engine#85]
I could be doing something wrong but I expected this to return true because they are mathematically equal according to the documentation. 
![Screenshot 2023-07-01 184438](https://github.com/cortex-js/compute-engine/assets/116941834/3c6b40a3-60bd-4d71-bee8-4c6556497ec4)
![Screenshot 2023-07-01 184509](https://github.com/cortex-js/compute-engine/assets/116941834/559d1186-dfc1-4dbf-8de1-bd9ac466f2f2)

**Comment by arnog** [comment]
The expected answer can be obtained by applying `Simplify` to both arguments. 

I'll consider adding that by default to the definition of `Equal`...
