### ISSUE TITLE
Issues with rational expressions

### ISSUE THREAD

**Issue by fredekr** [cortex-js/compute-engine#87]
There seems to be some problems with simple rational expressions that have sums/differences in the numerator or denominator. Interestingly, our use involves numerical substitution, which also fails.

Below are some screenshots from our use, and below that are some tests I did on the demo page. I suspect if the demo page starts to work properly, then our use will work too.

Our examples (these should all be equivalent to the expected answer):
<img width="686" alt="image" src="https://github.com/cortex-js/cortexjs.io/assets/56795542/7d78474e-18a3-42c5-b512-c8a45a4c43da">

Examples from demo page (these should all simplify/evaluate to zero):
Success:
<img width="647" alt="image" src="https://github.com/cortex-js/cortexjs.io/assets/56795542/190b4fd2-6e16-43d7-b0c8-1346914ceda1">

Success:
<img width="561" alt="image" src="https://github.com/cortex-js/cortexjs.io/assets/56795542/cac03a43-710c-48fa-930a-b464b3b3d57e">

Fail:
<img width="423" alt="image" src="https://github.com/cortex-js/cortexjs.io/assets/56795542/ed64d555-12ee-4190-94ee-ac80a5827600">

**Comment by arnog** [comment]
Hmm... that's an interesting issue.

`simplify()` does not guarantee it will always provide the "most simplified" version of an expression. For various reasons, it's actually difficult to define what "most simplified" means, and there are also performance tradeoffs.

I can see how the result with the expressions you have would be unexpected, though.

In your particular case, you can get what you want by applying `Expand` before simplify. In other words: `ce.simplify(ce.box(["Expand", expr"]))`.

Maybe that should just be done automatically. I'll consider it, but in the meantime you have a workaround that should satisfy your requirements.

**Comment by fredekr** [comment]
Thanks for your response. As you note, "simplify" may not behave as
expected. We have observed this in practice as well. So,  in our use case,
we instead ask ComputeEngine to substitute values for the variables to
establish equivalency, and that fails as well. Any ideas why that might be
happening?

**Comment by arnog** [comment]
It's hard to tell in general. Would you have some specific examples to share?

**Comment by fredekr** [comment]
Thanks for the response. I'm not the developer but we've got one working on implementing your suggestion. We will get back to you when we see how that goes.

**Comment by arnog** [comment]
Fixed now. Simplification has been improved.
