### ISSUE TITLE
Adding a custom variable creating error during evaluation

### ISSUE THREAD

**Issue by AbhishekNayak007** [cortex-js/compute-engine#89]
## Code
```
import { ComputeEngine } from "@cortex-js/compute-engine";
let exp = computingEngine.parse('speed+10');
computingEngine.set({ speed : 10 });
console.log(exp?.N().valueOf());  // cannot be evaluated 
```

**I am using mathlive virtual keyboard there I have created a custom button named as speed so when from that keyboard I click on speed then add then 10 it must give the output of 20 as I am using computing engine for setting the value of speed to 10 then evaluating the value**

**showing this console.log**
["Add",["Multiply","7.389056098930650227230427460575007813180315570551847324087127822522573796079057763384312485079121792","d","p","s"],10]

**Expected Output**
20

**Comment by arnog** [comment]
You need to wrap the multi-character identifier: `\mathrm{speed}+10`

**Comment by AbhishekNayak007** [comment]
I have added custom variables using the method you showed but when i am pressing delete option it is deleting character by character but i need that it must delete the complete character at once means delete  ```\mathrm{speed} ``` when i press backspace

**Comment by arnog** [comment]
To do this, define a macro and set `captureSelection` to `true`. See https://cortexjs.io/mathlive/guides/macros/
