### ISSUE TITLE
Integrals don't get serialized correctly

### ISSUE THREAD

**Issue by stefnotch** [cortex-js/compute-engine#9]
**To reproduce:**
1. Type in or copy in `\int_{\placeholder{⬚}}^{\placeholder{⬚}}3x`
2. Copy as mathjson. The result is `["Multiply",["Integral","","Missing","Missing"],{"num":"3"},"x"]`

You can also try it rather nicely on this page
https://cortexjs.io/compute-engine/demo/

**Comment by arnog** [comment]
Integrals now do get serialized correctly.
