### ISSUE TITLE
Outputs unexpected result for sum

### ISSUE THREAD

**Issue by stefnotch** [cortex-js/compute-engine#93]
Why does the infinite sum output a numerical value?
![image](https://github.com/cortex-js/compute-engine/assets/10220080/13963134-a680-4e13-8691-7a5aa23a757b)

**Steps to reproduce**
1. Go to https://cortexjs.io/compute-engine/demo/
2. Input `$$ \sum_{x=0}^{n}(1) $$`

There's also a bonus one, that I find especially fascinating
![image](https://github.com/cortex-js/compute-engine/assets/10220080/7089bbf1-4630-41c3-b6d0-042dfbab387e)

**Comment by arnog** [comment]
When you request a numerical evaluation (with `N()`) the compute engine will attempt to provide an approximation of one. For sums, infinity is hard-coded at 10e6. For convergent series, this can provide a useful approximation. For divergent or pathological, the approximation is less useful.

That said, it looks like the approximations are off by one, which is an error.

**Comment by stefnotch** [comment]
Ah, I see. That does make sense.

Would it be worthwhile to run the compute engine in a web worker in the future, since constructing cases that hang the browser for extended periods of time is reasonably easy? Or, have a note in the documentation about "use web worker, it might be a good idea".
e.g. $\sum_{i=0}^n i \cdot \sum_{j=0}^i 1$ will hang the browser for a while, without giving the user a chance to edit their input.

**Comment by arnog** [comment]
Yes, there are many operations that could take a (very) long time to complete. Using web workers is indeed a good strategy in that case.
