### ISSUE TITLE
Adding some function such as Expand and Rational to the virtual keyboard

### ISSUE THREAD

**Issue by rs-mobitech** [cortex-js/compute-engine#96]
You are using these in your demo, but from what I can see, there is no way to enter these using the virtual keyboard.  Could these functions be added as additional keys that could be tapped?

**Comment by arnog** [comment]
You can input them using the "abc" virtual keyboard.

**Comment by rs-mobitech** [comment]
I tried to input the word Rational(

<img width="550" alt="Screenshot 2023-08-25 at 11 53 22" src="https://github.com/cortex-js/compute-engine/assets/39233783/6eb0e777-238e-41a8-b3e0-7bce99049a58">

Is there a different way that I should be doing this, as I could not duplicate the way Rational( is entered in your example?

**Comment by arnog** [comment]
Did you use a physical keyboard or the virtual keyboard?
Could you try it again? It seems to work for me.

**Comment by rs-mobitech** [comment]
I tried again just now.  Yes, it works okay on the compute engine demo, but I realize now that I tried it on the MathLive demo page.  When I am on the MathLive page and enter it in using the physical or virtual keyboards, it does not work.

**Comment by arnog** [comment]
Ah, OK, that makes sense. The MathLive Demo page is not setup to recognize multicharacter identifiers. The Compute Engine demo page is. See https://cortexjs.io/mathlive/guides/shortcuts/#multicharacter-symbol for info on how to configure a mathfield to recognize multicharacter symbols.

**Comment by rs-mobitech** [comment]
My application is using the Compute Engine, but I think what you are saying is that there were some changes made to the demo page, perhaps to add values for onInlineShortcut.  Can you point me to a place where the multicharacter identifiers are, so that I can look into adding that to my application.  Thanks

**Comment by arnog** [comment]
Yes, see here: https://cortexjs.io/mathlive/guides/shortcuts/#multicharacter-identifiers

**Comment by rs-mobitech** [comment]
Thanks, but what I was meaning was, is there a line in the code of cortex.mjs where it is set up to recognize for example "Rational"? 

I would like to try and learn from your code, so I can understand more about how the application works.

**Comment by arnog** [comment]
Ah, OK. You can find the relevant code [here](https://github.com/cortex-js/cortexjs.io/blob/master/src/_pages/compute-engine-demo.html) at line 644.
