### ISSUE TITLE
Problems entering ["Integrate", ["Sin", x], "x"] in the mathJSON field

### ISSUE THREAD

**Issue by rs-mobitech** [cortex-js/compute-engine#97]
I tried to duplicate some mathJSON that you had as an example in your CortexJS documentation

<img width="415" alt="Screenshot 2023-08-25 at 12 45 28" src="https://github.com/cortex-js/compute-engine/assets/39233783/6650a0ec-63c0-49be-92c2-ce917ac41191">

but this resulted in an error

<img width="843" alt="Screenshot 2023-08-25 at 12 46 20" src="https://github.com/cortex-js/compute-engine/assets/39233783/4f173ee2-2d6c-4438-8def-6327b4acc652">

Can you give some advice.  Is this because the functionality for Integral is not yet implemented, or some mistake that I am making? 

Thanks

**Comment by arnog** [comment]
The `x` should be surrounded by quotes. The documentation has been updated.

**Comment by rs-mobitech** [comment]
I tried entering the corrected code in the CortexDemo page, but when I entered it, nothing happened

<img width="842" alt="Screenshot 2023-08-26 at 17 23 13" src="https://github.com/cortex-js/compute-engine/assets/39233783/42a1c390-d812-4200-bab9-2107a71a5f97">
