### ISSUE TITLE
mathJSON area information being cut off 

### ISSUE THREAD

**Issue by rs-mobitech** [cortex-js/compute-engine#98]
When tapping on your examples, I see the height allocated to the mathJSON area is not enough so there's some cut off.  

<img width="777" alt="Screenshot 2023-08-25 at 14 23 01" src="https://github.com/cortex-js/compute-engine/assets/39233783/670a1fd0-110c-475f-9d95-d36c00ec4646">

<img width="818" alt="Screenshot 2023-08-25 at 14 22 58" src="https://github.com/cortex-js/compute-engine/assets/39233783/febc852c-31ca-4c39-bf02-b7987435859e">

**Comment by arnog** [comment]
This is a text area. It can be resized using the resize handle at the bottom right of the field.

**Comment by arnog** [comment]
The website has been updated to automatically resize the textarea when needed.
