### ISSUE TITLE
\prod_{n=1}^8n seems to produce the wrong mathJSON

### ISSUE THREAD

**Issue by rs-mobitech** [cortex-js/compute-engine#99]
Here is what happened when I entered this on the demo page.  

<img width="812" alt="Screenshot 2023-08-25 at 14 42 03" src="https://github.com/cortex-js/compute-engine/assets/39233783/c34a826c-d1a5-41e4-b90d-eac70466a8e2">

From what I see, it ignores the lower value and uses the upper value twice

**Comment by arnog** [comment]
Fixed now.
